[phases.setup]
nixPkgs = ["nodejs_20", "npm-10_x"]

[phases.install]
cmds = ["npm ci --production=false --prefer-offline"]

[phases.build]
cmds = ["npm run build 2>&1 || (echo 'Build failed' && exit 1)"]

[start]
cmd = "npm start"

[variables]
NODE_ENV = "production"
NPM_CONFIG_PRODUCTION = "false"
NODE_OPTIONS = "--max-old-space-size=4096"
